// <auto-generated />
namespace EFTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NombrePorNombresAlumno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NombrePorNombresAlumno));
        
        string IMigrationMetadata.Id
        {
            get { return "201803281830413_NombrePorNombresAlumno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
